### ISSUE TITLE
App gets crashed after upgrade from the version 1.2.2 to 1.2.3

### ISSUE THREAD

**Issue by quannguyen14091986** [serso/android-checkout#180]
Hi! My app gets crashed after I upgraded from the version 1.2.2 to 1.2.3, and Android studio log console displays the error message

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/play_billing/zzc;
        at com.android.vending.billing.InAppBillingServiceImpl.make(InAppBillingServiceImpl.java:31)
        at org.solovyev.android.checkout.Billing$DefaultServiceConnector$1.onServiceConnected(Billing.java:1307)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.play_billing.zzc" on path: DexPathList[[zip file "/data/app/~~vMLmWVS881aUevpukdylNg==/com.norwoodsystems.worldphone-7P36lX2uMjVA3tvWMSrZUg==/base.apk"],nativeLibraryDirectories=[/data/app/~~vMLmWVS881aUevpukdylNg==/com.norwoodsystems.worldphone-7P36lX2uMjVA3tvWMSrZUg==/lib/arm64, /data/app/~~vMLmWVS881aUevpukdylNg==/com.norwoodsystems.worldphone-7P36lX2uMjVA3tvWMSrZUg==/base.apk!/lib/arm64-v8a, /system/lib64]]

I would appreciate if someone can give me a help

**Comment by cupnoodle** [comment]
How did you upgrade to 1.2.3? I changed to 1.2.3 and Android studio says "Could not determine artifacts for org.solovyev.android:checkout:1.2.3"

**Comment by serso** [comment]
This is strange and suspicious - I have no troubles releasing the reference app. Please check your project dependencies, maybe something depends on the other version of the Billing Client lib from Google?
